### ISSUE TITLE
How to install and get running local and server?

### ISSUE THREAD

**Issue by coding-to-music** [AhmadChaiban/COVID-19-Dashboard#1]
Great site, I've looked at many, nice semi-dark theme and straightforward logical widgets.
I forked and cloned to my laptop, how do I display it locally?
What code would get deployed to server?
I don't see a npm run serve

**Comment by AhmadChaiban** [comment]
Hello! Locally I just run index.html on a live server (using VS code).

**Comment by coding-to-music** [comment]
ok cool I installed http-server and now it's coming up on 8080

how about getting the tsv and csv files? I see an error in the terminal

**Comment by coding-to-music** [comment]
/world_covid.tsv
/CountryData/cases_per_day_diff_all.csv
/CountryData/cases_per_day_agg_all.csv

**Comment by AhmadChaiban** [comment]
Ah. Just run the dataFetch.py file, it will retrieve all the data files. Make sure you set up the right directory folders beforehand. I will add this as part of the documentation.

**Comment by coding-to-music** [comment]
when I go into the DataFetchers directory and execute this:
python3 dataFetch.py 

I get this:
  File "dataFetch.py", line 31
    all_country_cases_per_day += (f"{date}, {confirmed}, {recovered}, {deaths}, {active}, {name_data_instance[1].replace(',','')}\n")
                                                                                                                                   ^
SyntaxError: invalid syntax

**Comment by AhmadChaiban** [comment]
Which version of python are you using?

**Comment by coding-to-music** [comment]
What directory do I want to be in, and are their other directories or files it is looking for?
3.5.3

**Comment by AhmadChaiban** [comment]
Ah, I’m using f-strings, which are only valid for python 3.6 and up. As for the directory, you have to go to the root directory, create a folder (you can find its name in dataFetch.py) and the files will be automatically placed there by dataFetch.py

**Comment by AhmadChaiban** [comment]
Hold on. I think some files necessary for dataFetch are missing from the repo. I will add them now.

**Comment by AhmadChaiban** [comment]
Just pushed the file. Country_id_names.tsv

**Comment by coding-to-music** [comment]
any idea how I would sync my laptop from my github which is a fork of yours?

**Comment by AhmadChaiban** [comment]
Not sure tbh. I guess you have to either re-fork or clone the repo?

**Comment by coding-to-music** [comment]
Good question there is a description but it had a button I could press but I don't see that button. Meanwhile I've copied to a new file I created. Need to upgrade my python do you use pyenv or virtualenv ?

**Comment by AhmadChaiban** [comment]
Alright! This is the one I use https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by coding-to-music** [comment]
Conda is very cool thanks for that link. Easy to change environments. Modified .bashrc 
I had to add pandas too via 
conda install pandas 
Getting this message:
No such file or directory: '../CountryData/cases_per_day_agg_all.csv'

**Comment by coding-to-music** [comment]
(py38env) home@penguin:~/projects/COVID-19-Dashboard/DataFetchers$ mkdir ../CountryData
(py38env) home@penguin:~/projects/COVID-19-Dashboard/DataFetchers$ python Agg_data.py 
(py38env) home@penguin:~/projects/COVID-19-Dashboard/DataFetchers$ python dataFetch.py 

Hey it worked! Thank you so much, very cool!

**Comment by coding-to-music** [comment]
Something to think about is documenting how to run something on the EC2 not sure what is run or how to monitor it or where it delivers files?

**Comment by coding-to-music** [comment]
Easy to understand framework - can extend it & modify the data & content, add more routes etc nice project good work thanks

**Comment by AhmadChaiban** [comment]
Knock yourself out!
